export const APP_CHANGE_THEME = 'APP_CHANGE_THEME'

export const USER_LOGIN  = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const API_REQUEST_START = 'API_REQUEST_START'
export const API_REQUEST_END   = 'API_REQUEST_END'
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR'
